CONFIG_FLASH=y

CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x7000

# hash verify only
CONFIG_BOOT_SIGNATURE_TYPE_NONE=y

# configure mcuboot to make second slot as ota
CONFIG_BOOT_FIRMWARE_LOADER=y
CONFIG_BOOT_BOOTSTRAP=y

# not necessary but about 4KB saved
CONFIG_LTO=y
CONFIG_ISR_TABLES_LOCAL_DECLARATION=y
