CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_MANUFACTURER="SlimeVR"
CONFIG_USB_DEVICE_PRODUCT="Butterfly P4R11"

CONFIG_BATTERY_USE_REG_BUCK_MAPPING=y
CONFIG_LED_RGB_COLOR=y
CONFIG_SENSOR_ROTATION_90=y

# MAG on aux I2C yet not supported #77
CONFIG_SENSOR_USE_MAG=n
