CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_MANUFACTURER="SlimeVR"
CONFIG_USB_DEVICE_PRODUCT="SlimeVR Butterfly P4"

CONFIG_BATTERY_USE_REG_BUCK_MAPPING=y
CONFIG_LED_RGB_COLOR=y
CONFIG_SENSOR_ROTATION_90=y

CONFIG_SENSOR_USE_MAG=n
